#!/bin/bash
cd "$(dirname "$0")"

ver=$1

url=https://nodejs.org/dist/v$ver
file=node-v$ver

if [ "$ver" == "" ]; then
  echo "ERROR: missing version # on the command line"
  exit 1
fi

echo " "  
echo "######## Installing nodejs v$ver ########"

os=`uname -s`
if [ "$os" == "Darwin" ]; then
  flavor=darwin-x64
elif [ "$os" == "Linux" ]; then
  yum --version > /dev/null 2>&1
  rc=$?
  arch=`arch`
  if [ "$rc" == "0" ] && [ "$arch" == "x86_64" ]; then
    flavor=linux-x64
  elif [ "$arch" == "aarch64" ]; then
    flavor=linux-arm64
  else
    echo "$arch is not presently support"
  fi
fi

dir=$file-$flavor
full_file=$dir.tar.xz

rm -f $full_file*
rm -f postgrest

echo " downloading $full_file from $url .."
wget -q $url/$full_file
rc=$?
if [ "$rc" != "0" ]; then
  echo "ERROR: $ver not found or cannot download"
  exit 1
fi

echo " extracting $full_file ... "
rm -rf $dir
tar -xf $full_file
rc=$?
if [ "$rc" != "0" ]; then
  exit 1
else
  rm $full_file*
fi

echo " modifying directory structure"
cp -r $dir/* .

echo " cleaning up"
rm -rf $dir

port=3000
##echo " creating default config file pgrest.conf with following lines:"
##cat << EOF > pgrest.conf
##db-uri = "postgres://postgres@localhost:$port/postgres"
##db-schemas = "spock"
##db-anon-role = "web_anon"
##EOF
##cat pgrest.conf

logdir="data/logs/nodejs"
echo "  log directory: $logdir"
mkdir -p ../$logdir

if [[ "$isSTART" == "True" ]]; then
  cd ..
  ./io start nodejs
fi



