site_name: ToroDB Stampede
theme: readthedocs
pages:
  - 'Welcome': index.md
  - 'About': about.md
  - 'Quickstart': quickstart.md
  - Installation and configuration:
    - 'Prerequisites': installation/prerequisites.md
    - 'Installation With Docker': installation/docker.md
    - 'Installation With Binaries': installation/binaries.md
    - 'Installation With SNAP': installation/snap.md
    - 'Installation For Ubuntu/Debian': installation/deb.md
    - 'Installation For Fedora/CentOS': installation/rpm.md
    - 'Installation From Source Code': installation/source-code.md
  - Configuration:
    - 'Options or File': configuration/index.md
    - 'PostgreSQL Connectivity': configuration/postgresql-connectivity.md
    - 'MySQL Connectivity': configuration/mysql-connectivity.md
    - 'MongoDB Connectivity': configuration/mongodb-connectivity.md
    - 'Filtered Replication': configuration/filtered-replication.md
    - 'Off Heap Buffer': configuration/bufferOffHeap.md
    - 'Options Reference': configuration/options-reference.md
    - 'PostgreSQL Configuration Tips': configuration/postgresql-configuration-tips.md
    - 'JVM Configuration Tips': configuration/jvm-configuration-tips.md
  - 'The Relational Schema': relational-schema.md
  - 'Trouble Shooting': trouble-shooting.md
  - 'Metrics': metrics.md
  - 'FAQ': faq.md
  - 'Glossary': glossary.md
extra_css:
  - css/8kdata.css
markdown_extensions:
  - admonition:
google_analytics: ['UA-44578894-3', 'www.torodb.com']
