#!/bin/bash
cd "$(dirname "$0")"

port=5432
echo " creating default file postgrest.conf:"
cat << EOF > postgrest.conf
db-uri = "postgres://postgres@localhost:$port/demo"
db-schemas = "spock"
db-anon-role = "postgres"
EOF
#cat postgrest.conf

logdir="data/logs/postgrest"
echo "  log directory: $logdir"
mkdir -p ../$logdir

sudo dnf module install nodejs:18
sudo npm install -g swagger-ui-dist
sudo npm install -g http-server

if [[ "$isSTART" == "True" ]]; then
  cd ..
  ./io start postgrest
fi


