#!/bin/bash
cd "$(dirname "$0")"

sudo cp bin/pgbackrest  /usr/bin
sudo chmod 755 /usr/bin/pgbackrest

sudo mkdir -p -m 770 /var/log/pgbackrest
sudo chown $USER:$USER /var/log/pgbackrest
sudo mkdir -p /etc/pgbackrest
sudo mkdir -p /etc/pgbackrest/conf.d
sudo touch /etc/pgbackrest/pgbackrest.conf
sudo chmod 640 /etc/pgbackrest/pgbackrest.conf
sudo chown $USER:$USER /etc/pgbackrest/pgbackrest.conf

sudo mkdir -p /var/lib/pgbackrest
sudo chmod 750 /var/lib/pgbackrest
sudo chown $USER:$USER /var/lib/pgbackrest

cp pgbackrest.conf /etc/pgbackrest/pgbackrest.conf
rm -rf lib
rm -rf share

