FROM rockylinux:8

LABEL maintainer="OSCG-IO team"

SHELL ["/bin/bash", "-c"]

USER root

RUN yum update -y \
    && yum install -y wget curl git
RUN yum install -y python3 python3-devel 

#WORKDIR /opt
#RUN python3 -c "$(curl -fsSL https://oscg-io-download.s3.amazonaws.com/REPO/install.py)"
#WORKDIR /opt/oscg
#RUN ./io install pg14

EXPOSE 5432
EXPOSE 22

CMD /bin/bash
