#!/bin/bash
cd "$(dirname "$0")"

ver=$1
port=$2
url=https://github.com/PostgREST/postgrest/releases/download/v$ver
file=postgrest-v$ver
if [ "$port" == "" ]; then
  port="5432"
fi

if [ "$ver" == "" ]; then
  echo "ERROR: missing version # on the command line"
  exit 1
fi

echo ""  
echo "### Installing PostgREST v$ver ###"

os=`uname -s`
if [ "$os" == "Darwin" ]; then
  flavor=macos-x64
elif [ "$os" == "Linux" ]; then
  yum --version > /dev/null 2>&1
  rc=$?
  arch=`arch`
  if [ "$rc" == "0" ] && [ "$arch" == "x86_64" ]; then
    flavor=linux-static-x64
  elif [ "$arch" == "aarch64" ]; then
    flavor=ubuntu-aarch64
  else
    echo "$arch is not presently support"
  fi
fi

full_file=$file-$flavor.tar.xz

rm -f $full_file*
rm -f postgrest


wget $url/$full_file
rc=$?
if [ "$rc" != "0" ]; then
  echo "ERROR: $ver not found"
  exit 1
fi

tar -xf $full_file
rc=$?
if [ "$rc" != "0" ]; then
  exit 1
else
  rm $full_file*
fi

cat << EOF > rest.conf
db-uri = "postgres://postgres@localhost:$port/postgres"
db-schemas = "spock"
db-anon-role = "web_anon"
EOF

mkdir -p ../data/logs/postgrest


