#!/bin/bash
cd "$(dirname "$0")"

ver="$1"

if [ "$ver" == "" ]; then
  echo "ERROR: version num parm required"
  exit 1
fi

echo " "
echo "## INSTALL PGE v$1 ############################################"

cd ..

./io install pg14 --start 
./io install citus spock audit cron background timescale postgis
./io install anon

